bot:
  prefix: '!'
  token: BotToken-ABCDEFGHIJKLMNOPQRSTUVWXYZ.12233344445555566666677
  activity: playing
  action: with other Bots
permission:
  staff-role-id: '000000000000000000'
  owner-id: '000000000000000000'
command:
  dadjoke:
    api: https://icanhazdadjoke.com/
    connection-timeout: '5000'
    read-timeout: '5000'
verbose: false
